///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDemoAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("cae2f1d7-af6a-4620-bf21-798e3fa036bb")]
    public partial class RxDemoAppRepository : RepoGenBaseFolder
    {
        static RxDemoAppRepository instance = new RxDemoAppRepository();
        RxDemoAppRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        RxDemoAppRepositoryFolders.List1000AppFolder _list1000;
        RxDemoAppRepositoryFolders.HOTELPLANISPHEREテスト自動化練習サイトAppFolder _hotelplanisphereテスト自動化練習サイト;

        /// <summary>
        /// Gets the singleton class instance representing the RxDemoAppRepository element repository.
        /// </summary>
        [RepositoryFolder("cae2f1d7-af6a-4620-bf21-798e3fa036bb")]
        public static RxDemoAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDemoAppRepository() 
            : base("RxDemoAppRepository", "/", null, 0, false, "cae2f1d7-af6a-4620-bf21-798e3fa036bb", ".\\RepositoryImages\\RxDemoAppRepositorycae2f1d7.rximgres")
        {
            _rxmainframe = new RxDemoAppRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new RxDemoAppRepositoryFolders.List1000AppFolder(this);
            _hotelplanisphereテスト自動化練習サイト = new RxDemoAppRepositoryFolders.HOTELPLANISPHEREテスト自動化練習サイトAppFolder(this);
        }

#region Variables

        string _Department = "Project Management";

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("101d24a0-d8d4-4717-bdb7-48496572754a")]
        public string Department
        {
            get { return _Department; }
            set { _Department = value; }
        }

        string _Gender = "Male";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("bb7cb25f-f20f-4a1f-a3a6-aa88aeaeaf41")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cae2f1d7-af6a-4620-bf21-798e3fa036bb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("2a0d33de-7233-4fd3-9b0f-80df777abcc5")]
        public virtual RxDemoAppRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("80ebfae4-7f7b-4189-9f8a-97467c38b8b3")]
        public virtual RxDemoAppRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The HOTELPLANISPHEREテスト自動化練習サイト folder.
        /// </summary>
        [RepositoryFolder("4d922682-9c74-4854-9202-ba8b7a7a2aa3")]
        public virtual RxDemoAppRepositoryFolders.HOTELPLANISPHEREテスト自動化練習サイトAppFolder HOTELPLANISPHEREテスト自動化練習サイト
        {
            get { return _hotelplanisphereテスト自動化練習サイト; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDemoAppRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a0d33de-7233-4fd3-9b0f-80df777abcc5")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RxDemoAppRepositoryFolders.RxTabStandard1Folder _rxtabstandard1;
            RxDemoAppRepositoryFolders.RxTabUIElementsFolder _rxtabuielements;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _btnbutton1Info;
            RxStudioLogoInfoClass _rxstudiologoInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@automationid='RxMainFrame']", parentFolder, 30000, null, true, "2a0d33de-7233-4fd3-9b0f-80df777abcc5", "")
            {
                _rxtabstandard1 = new RxDemoAppRepositoryFolders.RxTabStandard1Folder(this);
                _rxtabuielements = new RxDemoAppRepositoryFolders.RxTabUIElementsFolder(this);
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "5496851c-b600-47da-8993-786b59670f5d");
                _btnbutton1Info = new RepoItemInfo(this, "BtnButton1", "?/?/tabpage[@automationid='RxTabUIElements']/?/?/button[@text='Reset']", ".//button[@text='Reset']", 30000, null, "28716b2d-211b-420a-974e-3d81610774c5");
                _rxstudiologoInfo = new RxStudioLogoInfoClass(this);
            }

            /// <summary>
            /// The RxStudioLogoInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("7ccadb24-87f8-4dbc-baf4-8b231a3d6b72")]
            public class RxStudioLogoInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RxStudioLogoInfoClass class constructor.
                /// </summary>
                public RxStudioLogoInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RxStudioLogo", "?/?/tabpage[@automationid='RxTabIntroduction']/picture[@automationid='RxStudioLogo']", 30000, null, "7ccadb24-87f8-4dbc-baf4-8b231a3d6b72")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("94273434-47bb-4b4f-b3a6-9b93e3c1c0e6")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("94273434-47bb-4b4f-b3a6-9b93e3c1c0e6");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("94273434-47bb-4b4f-b3a6-9b93e3c1c0e6")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("94273434-47bb-4b4f-b3a6-9b93e3c1c0e6", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a0d33de-7233-4fd3-9b0f-80df777abcc5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a0d33de-7233-4fd3-9b0f-80df777abcc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("5496851c-b600-47da-8993-786b59670f5d")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("5496851c-b600-47da-8993-786b59670f5d")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The BtnButton1 item.
            /// </summary>
            [RepositoryItem("28716b2d-211b-420a-974e-3d81610774c5")]
            public virtual Ranorex.Button BtnButton1
            {
                get
                {
                    return _btnbutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnButton1 item info.
            /// </summary>
            [RepositoryItemInfo("28716b2d-211b-420a-974e-3d81610774c5")]
            public virtual RepoItemInfo BtnButton1Info
            {
                get
                {
                    return _btnbutton1Info;
                }
            }

            /// <summary>
            /// The RxStudioLogo item.
            /// </summary>
            [RepositoryItem("7ccadb24-87f8-4dbc-baf4-8b231a3d6b72")]
            public virtual Ranorex.Picture RxStudioLogo
            {
                get
                {
                    return _rxstudiologoInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The RxStudioLogo item info.
            /// </summary>
            [RepositoryItemInfo("7ccadb24-87f8-4dbc-baf4-8b231a3d6b72")]
            public virtual RxStudioLogoInfoClass RxStudioLogoInfo
            {
                get
                {
                    return _rxstudiologoInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard1 folder.
            /// </summary>
            [RepositoryFolder("5a36e37c-8441-448c-9b3d-349c70aab2fc")]
            public virtual RxDemoAppRepositoryFolders.RxTabStandard1Folder RxTabStandard1
            {
                get { return _rxtabstandard1; }
            }

            /// <summary>
            /// The RxTabUIElements folder.
            /// </summary>
            [RepositoryFolder("7c3f3d9a-4b67-40d4-b35f-134d716b2863")]
            public virtual RxDemoAppRepositoryFolders.RxTabUIElementsFolder RxTabUIElements
            {
                get { return _rxtabuielements; }
            }
        }

        /// <summary>
        /// The RxTabStandard1Folder folder.
        /// </summary>
        [RepositoryFolder("5a36e37c-8441-448c-9b3d-349c70aab2fc")]
        public partial class RxTabStandard1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtabstandardInfo;
            RepoItemInfo _button閉じるInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _エントリー1Info;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _button開くInfo;

            /// <summary>
            /// Creates a new RxTabStandard1  folder.
            /// </summary>
            public RxTabStandard1Folder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard1", "?/?/tabpage[@automationid='RxTabStandard']", parentFolder, 30000, null, false, "5a36e37c-8441-448c-9b3d-349c70aab2fc", "")
            {
                _rxtabstandardInfo = new RepoItemInfo(this, "RxTabStandard", "", "", 30000, null, "9436a092-0b3a-4855-9772-83c2ce61456c");
                _button閉じるInfo = new RepoItemInfo(this, "Button閉じる", "?/?/button[@accessiblename='閉じる']", "", 30000, null, "8b73b024-12b8-4e39-a2b1-b478d0e53383");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@text=$Gender]", "", 30000, null, "2652cbc0-d3e0-4e25-9801-e2946d5a75f9");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "f1cb316d-4f16-4289-b291-fbb11968f312");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "5594516d-da98-4729-8ecf-59e6412094cf");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@automationid='txtAge']", "", 30000, null, "6407c34a-d5ac-43b5-a7db-15af5b187fca");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@text='Add entry']", "", 30000, null, "ab3168fb-c1dc-4f5f-a6f5-926679ceba9a");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@automationid='lblNumberOfPersonsNumber']", "", 30000, null, "73276401-2806-431d-a70e-4016489086ce");
                _エントリー1Info = new RepoItemInfo(this, "エントリー1", "list[@automationid='lstPersonList']/?/?/listitem[1]", "", 30000, null, "52c75f5a-c9da-4cc1-b83a-a79807f006e3");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@text='Delete entry']", "", 30000, null, "830a6374-1ae0-41ea-a563-c34e4a314d97");
                _button開くInfo = new RepoItemInfo(this, "Button開く", "?/?/button[@accessiblename='開く']", "", 30000, null, "8caa05b1-3df5-49e2-adda-d1c59d390c49");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5a36e37c-8441-448c-9b3d-349c70aab2fc")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a36e37c-8441-448c-9b3d-349c70aab2fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard item.
            /// </summary>
            [RepositoryItem("9436a092-0b3a-4855-9772-83c2ce61456c")]
            public virtual Ranorex.TabPage RxTabStandard
            {
                get
                {
                    return _rxtabstandardInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabStandard item info.
            /// </summary>
            [RepositoryItemInfo("9436a092-0b3a-4855-9772-83c2ce61456c")]
            public virtual RepoItemInfo RxTabStandardInfo
            {
                get
                {
                    return _rxtabstandardInfo;
                }
            }

            /// <summary>
            /// The Button閉じる item.
            /// </summary>
            [RepositoryItem("8b73b024-12b8-4e39-a2b1-b478d0e53383")]
            public virtual Ranorex.Button Button閉じる
            {
                get
                {
                    return _button閉じるInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button閉じる item info.
            /// </summary>
            [RepositoryItemInfo("8b73b024-12b8-4e39-a2b1-b478d0e53383")]
            public virtual RepoItemInfo Button閉じるInfo
            {
                get
                {
                    return _button閉じるInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("2652cbc0-d3e0-4e25-9801-e2946d5a75f9")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("2652cbc0-d3e0-4e25-9801-e2946d5a75f9")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f1cb316d-4f16-4289-b291-fbb11968f312")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f1cb316d-4f16-4289-b291-fbb11968f312")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("5594516d-da98-4729-8ecf-59e6412094cf")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("5594516d-da98-4729-8ecf-59e6412094cf")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("6407c34a-d5ac-43b5-a7db-15af5b187fca")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("6407c34a-d5ac-43b5-a7db-15af5b187fca")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("ab3168fb-c1dc-4f5f-a6f5-926679ceba9a")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("ab3168fb-c1dc-4f5f-a6f5-926679ceba9a")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("73276401-2806-431d-a70e-4016489086ce")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("73276401-2806-431d-a70e-4016489086ce")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The エントリー1 item.
            /// </summary>
            [RepositoryItem("52c75f5a-c9da-4cc1-b83a-a79807f006e3")]
            public virtual Ranorex.ListItem エントリー1
            {
                get
                {
                    return _エントリー1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The エントリー1 item info.
            /// </summary>
            [RepositoryItemInfo("52c75f5a-c9da-4cc1-b83a-a79807f006e3")]
            public virtual RepoItemInfo エントリー1Info
            {
                get
                {
                    return _エントリー1Info;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("830a6374-1ae0-41ea-a563-c34e4a314d97")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("830a6374-1ae0-41ea-a563-c34e4a314d97")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The Button開く item.
            /// </summary>
            [RepositoryItem("8caa05b1-3df5-49e2-adda-d1c59d390c49")]
            public virtual Ranorex.Button Button開く
            {
                get
                {
                    return _button開くInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button開く item info.
            /// </summary>
            [RepositoryItemInfo("8caa05b1-3df5-49e2-adda-d1c59d390c49")]
            public virtual RepoItemInfo Button開くInfo
            {
                get
                {
                    return _button開くInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUIElementsFolder folder.
        /// </summary>
        [RepositoryFolder("7c3f3d9a-4b67-40d4-b35f-134d716b2863")]
        public partial class RxTabUIElementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnbutton2Info;
            RepoItemInfo _actionsInfo;
            RepoItemInfo _ranorexrecorderInfo;
            RepoItemInfo _ranorexstudioInfo;
            RepoItemInfo _reportingInfo;
            RepoItemInfo _repositoryInfo;
            RepoItemInfo _testsuiteInfo;
            RepoItemInfo _testvalidationInfo;
            RepoItemInfo _ranorizeyourselfin20minutesInfo;
            RepoItemInfo _ranorexstudiofundamentalsInfo;

            /// <summary>
            /// Creates a new RxTabUIElements  folder.
            /// </summary>
            public RxTabUIElementsFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUIElements", "?/?/tabpage[@automationid='RxTabUIElements']", parentFolder, 30000, null, false, "7c3f3d9a-4b67-40d4-b35f-134d716b2863", "")
            {
                _btnbutton2Info = new RepoItemInfo(this, "BtnButton2", "?/?/button[@text='Shuffle']", "", 30000, null, "f5111000-142d-4de6-b158-c840adc759b8");
                _actionsInfo = new RepoItemInfo(this, "Actions", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Actions']", "", 30000, null, "5bc1bfc1-a857-4b54-802e-f90b6a66954f");
                _ranorexrecorderInfo = new RepoItemInfo(this, "RanorexRecorder", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Ranorex Recorder']", "", 30000, null, "cd773ff4-b9eb-421b-856c-aa711ba9b0c8");
                _ranorexstudioInfo = new RepoItemInfo(this, "RanorexStudio", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Ranorex Studio']", "", 30000, null, "ac01a97a-c19f-4f03-b32a-436c918ec21e");
                _reportingInfo = new RepoItemInfo(this, "Reporting", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Reporting']", "", 30000, null, "a851d81a-42c9-4794-a8c8-779c5d0285b9");
                _repositoryInfo = new RepoItemInfo(this, "Repository", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Repository']", "", 30000, null, "5f75f12c-12b0-461f-a62d-d9bf311fa58c");
                _testsuiteInfo = new RepoItemInfo(this, "TestSuite", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Test suite']", "", 30000, null, "9399e921-6464-4c69-998d-d1cdcff99094");
                _testvalidationInfo = new RepoItemInfo(this, "TestValidation", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename='Test validation']", "", 30000, null, "eabd5dd8-2737-4953-9bff-37f61a624a8f");
                _ranorizeyourselfin20minutesInfo = new RepoItemInfo(this, "RanorizeYourselfIn20Minutes", "tree[@automationid='treTestTreeView']//treeitem[@accessiblename>'Ranorize yourself in 20 m']", "", 30000, null, "3809686e-61b3-4936-9ad8-b6ef6bfaa5ab");
                _ranorexstudiofundamentalsInfo = new RepoItemInfo(this, "RanorexStudioFundamentals", "tree[@automationid='treTestTreeView']/?/?/treeitem[@accessiblename>'Ranorex Studio fundamenta']", "", 30000, null, "d693ff7a-60b9-470b-b8e9-59f7bf74b85d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c3f3d9a-4b67-40d4-b35f-134d716b2863")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c3f3d9a-4b67-40d4-b35f-134d716b2863")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnButton2 item.
            /// </summary>
            [RepositoryItem("f5111000-142d-4de6-b158-c840adc759b8")]
            public virtual Ranorex.Button BtnButton2
            {
                get
                {
                    return _btnbutton2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnButton2 item info.
            /// </summary>
            [RepositoryItemInfo("f5111000-142d-4de6-b158-c840adc759b8")]
            public virtual RepoItemInfo BtnButton2Info
            {
                get
                {
                    return _btnbutton2Info;
                }
            }

            /// <summary>
            /// The Actions item.
            /// </summary>
            [RepositoryItem("5bc1bfc1-a857-4b54-802e-f90b6a66954f")]
            public virtual Ranorex.TreeItem Actions
            {
                get
                {
                    return _actionsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Actions item info.
            /// </summary>
            [RepositoryItemInfo("5bc1bfc1-a857-4b54-802e-f90b6a66954f")]
            public virtual RepoItemInfo ActionsInfo
            {
                get
                {
                    return _actionsInfo;
                }
            }

            /// <summary>
            /// The RanorexRecorder item.
            /// </summary>
            [RepositoryItem("cd773ff4-b9eb-421b-856c-aa711ba9b0c8")]
            public virtual Ranorex.TreeItem RanorexRecorder
            {
                get
                {
                    return _ranorexrecorderInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexRecorder item info.
            /// </summary>
            [RepositoryItemInfo("cd773ff4-b9eb-421b-856c-aa711ba9b0c8")]
            public virtual RepoItemInfo RanorexRecorderInfo
            {
                get
                {
                    return _ranorexrecorderInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio item.
            /// </summary>
            [RepositoryItem("ac01a97a-c19f-4f03-b32a-436c918ec21e")]
            public virtual Ranorex.TreeItem RanorexStudio
            {
                get
                {
                    return _ranorexstudioInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio item info.
            /// </summary>
            [RepositoryItemInfo("ac01a97a-c19f-4f03-b32a-436c918ec21e")]
            public virtual RepoItemInfo RanorexStudioInfo
            {
                get
                {
                    return _ranorexstudioInfo;
                }
            }

            /// <summary>
            /// The Reporting item.
            /// </summary>
            [RepositoryItem("a851d81a-42c9-4794-a8c8-779c5d0285b9")]
            public virtual Ranorex.TreeItem Reporting
            {
                get
                {
                    return _reportingInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Reporting item info.
            /// </summary>
            [RepositoryItemInfo("a851d81a-42c9-4794-a8c8-779c5d0285b9")]
            public virtual RepoItemInfo ReportingInfo
            {
                get
                {
                    return _reportingInfo;
                }
            }

            /// <summary>
            /// The Repository item.
            /// </summary>
            [RepositoryItem("5f75f12c-12b0-461f-a62d-d9bf311fa58c")]
            public virtual Ranorex.TreeItem Repository
            {
                get
                {
                    return _repositoryInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Repository item info.
            /// </summary>
            [RepositoryItemInfo("5f75f12c-12b0-461f-a62d-d9bf311fa58c")]
            public virtual RepoItemInfo RepositoryInfo
            {
                get
                {
                    return _repositoryInfo;
                }
            }

            /// <summary>
            /// The TestSuite item.
            /// </summary>
            [RepositoryItem("9399e921-6464-4c69-998d-d1cdcff99094")]
            public virtual Ranorex.TreeItem TestSuite
            {
                get
                {
                    return _testsuiteInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TestSuite item info.
            /// </summary>
            [RepositoryItemInfo("9399e921-6464-4c69-998d-d1cdcff99094")]
            public virtual RepoItemInfo TestSuiteInfo
            {
                get
                {
                    return _testsuiteInfo;
                }
            }

            /// <summary>
            /// The TestValidation item.
            /// </summary>
            [RepositoryItem("eabd5dd8-2737-4953-9bff-37f61a624a8f")]
            public virtual Ranorex.TreeItem TestValidation
            {
                get
                {
                    return _testvalidationInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TestValidation item info.
            /// </summary>
            [RepositoryItemInfo("eabd5dd8-2737-4953-9bff-37f61a624a8f")]
            public virtual RepoItemInfo TestValidationInfo
            {
                get
                {
                    return _testvalidationInfo;
                }
            }

            /// <summary>
            /// The RanorizeYourselfIn20Minutes item.
            /// </summary>
            [RepositoryItem("3809686e-61b3-4936-9ad8-b6ef6bfaa5ab")]
            public virtual Ranorex.TreeItem RanorizeYourselfIn20Minutes
            {
                get
                {
                    return _ranorizeyourselfin20minutesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorizeYourselfIn20Minutes item info.
            /// </summary>
            [RepositoryItemInfo("3809686e-61b3-4936-9ad8-b6ef6bfaa5ab")]
            public virtual RepoItemInfo RanorizeYourselfIn20MinutesInfo
            {
                get
                {
                    return _ranorizeyourselfin20minutesInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioFundamentals item.
            /// </summary>
            [RepositoryItem("d693ff7a-60b9-470b-b8e9-59f7bf74b85d")]
            public virtual Ranorex.TreeItem RanorexStudioFundamentals
            {
                get
                {
                    return _ranorexstudiofundamentalsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioFundamentals item info.
            /// </summary>
            [RepositoryItemInfo("d693ff7a-60b9-470b-b8e9-59f7bf74b85d")]
            public virtual RepoItemInfo RanorexStudioFundamentalsInfo
            {
                get
                {
                    return _ranorexstudiofundamentalsInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("80ebfae4-7f7b-4189-9f8a-97467c38b8b3")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@automationid='ListBox']", parentFolder, 30000, null, true, "80ebfae4-7f7b-4189-9f8a-97467c38b8b3", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text=$Department]", "", 30000, null, "7054b58c-256a-4981-bf9a-7a0a93e871dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80ebfae4-7f7b-4189-9f8a-97467c38b8b3")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80ebfae4-7f7b-4189-9f8a-97467c38b8b3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("7054b58c-256a-4981-bf9a-7a0a93e871dc")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("7054b58c-256a-4981-bf9a-7a0a93e871dc")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

        /// <summary>
        /// The HOTELPLANISPHEREテスト自動化練習サイトAppFolder folder.
        /// </summary>
        [RepositoryFolder("4d922682-9c74-4854-9202-ba8b7a7a2aa3")]
        public partial class HOTELPLANISPHEREテスト自動化練習サイトAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ログインInfo;

            /// <summary>
            /// Creates a new HOTELPLANISPHEREテスト自動化練習サイト  folder.
            /// </summary>
            public HOTELPLANISPHEREテスト自動化練習サイトAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HOTELPLANISPHEREテスト自動化練習サイト", "/dom[@domain='hotel.testplanisphere.dev']", parentFolder, 30000, null, false, "4d922682-9c74-4854-9202-ba8b7a7a2aa3", "")
            {
                _ログインInfo = new RepoItemInfo(this, "ログイン", ".//li[#'login-holder']/a[@innertext='ログイン']", ".//li[#'login-holder']/a[@innertext='ログイン']", 30000, null, "e6c794fb-8234-4dca-8b42-c54d1d6db3c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d922682-9c74-4854-9202-ba8b7a7a2aa3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d922682-9c74-4854-9202-ba8b7a7a2aa3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ログイン item.
            /// </summary>
            [RepositoryItem("e6c794fb-8234-4dca-8b42-c54d1d6db3c2")]
            public virtual Ranorex.ATag ログイン
            {
                get
                {
                    return _ログインInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ログイン item info.
            /// </summary>
            [RepositoryItemInfo("e6c794fb-8234-4dca-8b42-c54d1d6db3c2")]
            public virtual RepoItemInfo ログインInfo
            {
                get
                {
                    return _ログインInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
