///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The エントリーの削除 recording.
    /// </summary>
    [TestModule("027bb9c0-0a68-442e-9ba5-43ee0aa4a286", ModuleType.Recording, 1)]
    public partial class エントリーの削除 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDemoAppRepository repository.
        /// </summary>
        public static RxDemoAppRepository repo = RxDemoAppRepository.Instance;

        static エントリーの削除 instance = new エントリーの削除();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public エントリーの削除()
        {
            NewVariable = "X";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static エントリーの削除 Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("91ebb1fe-dd72-45f5-bcb5-e62c230e224c")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.エントリー1' at 39;9.", repo.RxMainFrame.RxTabStandard1.エントリー1Info, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard1.エントリー1.Click("39;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.BtnDeletePerson' at 46;8.", repo.RxMainFrame.RxTabStandard1.BtnDeletePersonInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard1.BtnDeletePerson.Click("46;8");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.RxTabStandard' at Center.", repo.RxMainFrame.RxTabStandard1.RxTabStandardInfo, new RecordItemIndex(2));
            //repo.RxMainFrame.RxTabStandard1.RxTabStandard.Click();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
