///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The エントリーの登録 recording.
    /// </summary>
    [TestModule("bf68d766-1e4d-40cb-b9bb-46757808395c", ModuleType.Recording, 1)]
    public partial class エントリーの登録 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDemoAppRepository repository.
        /// </summary>
        public static RxDemoAppRepository repo = RxDemoAppRepository.Instance;

        static エントリーの登録 instance = new エントリーの登録();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public エントリーの登録()
        {
            FirstName = "Taro";
            LastName = "Yamada";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static エントリーの登録 Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("6d8ee8f1-7bb6-45ad-a5eb-3de3d32af84a")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("1178406e-b383-452f-b38b-1bdebd00d730")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("101d24a0-d8d4-4717-bdb7-48496572754a")]
        public string Department
        {
            get { return repo.Department; }
            set { repo.Department = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("bb7cb25f-f20f-4a1f-a3a6-aa88aeaeaf41")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.FirstName' at 69;9.", repo.RxMainFrame.RxTabStandard1.FirstNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard1.FirstName.Click("69;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstName' with focus on 'RxMainFrame.RxTabStandard1.FirstName'.", repo.RxMainFrame.RxTabStandard1.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard1.FirstName.PressKeys(FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.LastName' at 65;11.", repo.RxMainFrame.RxTabStandard1.LastNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard1.LastName.Click("65;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'RxMainFrame.RxTabStandard1.LastName'.", repo.RxMainFrame.RxTabStandard1.LastNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard1.LastName.PressKeys(LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.Button開く' at 9;13.", repo.RxMainFrame.RxTabStandard1.Button開くInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabStandard1.Button開く.Click("9;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ProjectManagement' at 92;10.", repo.List1000.ProjectManagementInfo, new RecordItemIndex(5));
            repo.List1000.ProjectManagement.Click("92;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.UpDownEdit' at 41;10.", repo.RxMainFrame.RxTabStandard1.UpDownEditInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabStandard1.UpDownEdit.Click("41;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'RxMainFrame.RxTabStandard1.UpDownEdit'.", repo.RxMainFrame.RxTabStandard1.UpDownEditInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard1.UpDownEdit.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '30' with focus on 'RxMainFrame.RxTabStandard1.UpDownEdit'.", repo.RxMainFrame.RxTabStandard1.UpDownEditInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard1.UpDownEdit.PressKeys("30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.RdbMale' at 11;12.", repo.RxMainFrame.RxTabStandard1.RdbMaleInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard1.RdbMale.Click("11;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.BtnAddPerson' at 68;11.", repo.RxMainFrame.RxTabStandard1.BtnAddPersonInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabStandard1.BtnAddPerson.Click("68;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
