///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The エントリー数の確認 recording.
    /// </summary>
    [TestModule("28970217-6108-4759-b64a-92805896632b", ModuleType.Recording, 1)]
    public partial class エントリー数の確認 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDemoAppRepository repository.
        /// </summary>
        public static RxDemoAppRepository repo = RxDemoAppRepository.Instance;

        static エントリー数の確認 instance = new エントリー数の確認();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public エントリー数の確認()
        {
            ValidateData = "3";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static エントリー数の確認 Instance
        {
            get { return instance; }
        }

#region Variables

        string _ValidateData;

        /// <summary>
        /// Gets or sets the value of variable ValidateData.
        /// </summary>
        [TestVariable("0ccd4759-3bc0-4149-af87-32b885588f10")]
        public string ValidateData
        {
            get { return _ValidateData; }
            set { _ValidateData = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text=$ValidateData) on item 'RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumber'.", repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, "Text", ValidateData, null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.OnFail});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
